site_name: Razor - Ultima Online Assistant
site_description: Razor is a free tool designed to help with simple tasks while playing Ultima Online
site_author: Project maintained by Mark Wagner (Quick)
site_url: http://www.uor-razor.com
copyright: Copyright 2020 - Mark Wagner (Quick)
google_analytics: ['UA-20537997-5', 'uor-razor.com']
repo_url: https://github.com/markdwags/Razor
repo_name: Razor
edit_uri: ""
nav:
- Home: index.md
- Install: install.md
- Download: download.md
- Release Notes: releasenotes.md
- Help:
    - General: help/general.md
    - Options: help/options.md    
    - Display/Counters: help/displaycounters.md
    - Arm/Dress: help/armdress.md
    - Skills: help/help/skills.md
    - Agents: help/agents.md
    - Filters: help/filters.md
    - Hot Keys: help/hotkeys.md
    - Macros: help/macros.md
    - Scripts: help/scripts.md
    - Friends: help/friends.md    
    - Screen Shots: help/screenshots.md
    - Advanced: help/advanced.md
- Razor Scripting Guide: http://www.uor-razor.com/guide
- UOAssist API: uoaapi.md
theme: 
    name: material    
    icon:
        repo: fontawesome/brands/github
    palette:
        primary: red
        accent: blue
markdown_extensions:
  - admonition
  - toc:
        baselevel: 3
plugins:
  - search