site_name: Razor - UO Assistant
site_description: Help guide for using the Ultima Online assistant client called Razor
site_author: Maintained by Quick, many contributed over the years
site_url: http://www.uor-razor.com/help
copyright: Copyright 2020 - Mark Wagner (Quick)
google_analytics: ['UA-20537997-5', 'uor-razor.com']
repo_url: https://github.com/markdwags/Razor
repo_name: Razor
edit_uri: ""
nav:
- Home: index.md
- Install: install.md
- Overview:
    - General: general.md
    - Options: options.md    
    - Display/Counters: displaycounters.md
    - Arm/Dress: armdress.md
    - Skills: skills.md
    - Agents: agents.md
    - Filters: filters.md
    - Hot Keys: hotkeys.md
    - Macros: macros.md
    - Scripts: scripts.md
    - Friends: friends.md    
    - Screen Shots: screenshots.md
    - Advanced: advanced.md
- Help: help.md
- UOA API: uoaapi.md
theme: 
    name: material    
    icon:
        repo: fontawesome/brands/github
    palette:
        primary: red
        accent: blue
markdown_extensions:
  - admonition
  - toc:
        baselevel: 3
plugins:
  - search