name: Build Site

on:
  push:
    branches:
      - master
    paths:
    - 'help/**'
  pull_request:
    branches:
      - master
    paths:
    - 'help/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./help
    strategy:
      matrix:
        python-version: [3.10]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material          
          pip install mkdocs-git-revision-date-plugin
      # Runs a single command using the runners shell
      - name: Build site
        run: mkdocs build

      # Setup AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./site s3://www.razorce.com